services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/symfony
      - ./storage:/var/www/symfony/public/storage
      - ./conf/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-gd.ini
      - ./conf/php.ini-development:/usr/local/etc/php/php.ini-development
    depends_on:
      - db
    networks:
      - dev-network
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    image: nginx:alpine
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/symfony
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - dev-network
    restart: always
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dev-network
    ports:
      - "3306:3306"

networks:
  dev-network:

volumes:
  db_data:
